FROM node:16

ARG MONGO_URI
ARG LOCAL_STRING
ARG JWT_SECRET
ARG JWT_LIFETIME
ARG TWILIO_ACCOUNT_SID
ARG TWILIO_AUTH_TOKEN
ARG TWILIO_PHONE_NUMBER

ENV MONGO_URI=$MONGO_URI
ENV LOCAL_STRING=$LOCAL_STRING
ENV JWT_SECRET=$JWT_SECRET
ENV JWT_LIFETIME=$JWT_LIFETIME
ENV TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID
ENV TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN
ENV TWILIO_PHONE_NUMBER=$TWILIO_PHONE_NUMBER

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "start"]